name: sign-keyless
on:
  workflow_call:
    inputs:
      image_digest:
        description: 'Fully-qualified image digest to verify (registry/image@sha256:digest)'
        required: true
        type: string
      cosign_version:
        description: 'The version of cosign to use'
        required: false
        type: string
        default: 'v2.0.1'
permissions:
  contents: read

jobs:
  sign-keyless:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      packages: write
      id-token: write # Needed for OIDC and keyless signing
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
        with:
          egress-policy: audit

      - name: Install Cosign
        uses: sigstore/cosign-installer@4959ce089c160fddf62f7b42464195ba1a56d382 # v3.6.0
        with:
          cosign-release: ${{ inputs.cosign_version }}
      - name: Check Cosign
        run: |
          cosign version
      - name: Auth Cosign
        run: |
          cosign login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Sign Image keyless
        env:
          COSIGN_YES: true
        run: |
          cosign sign ${{ inputs.image_digest }} \
              -a sha=${{ github.sha }} \
              -a run_id=${{ github.run_id }} \
              -a run_attempt=${{ github.run_attempt }} \
              -a tag=${{ env.GITHUB_REF_NAME }}
