name: test

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.20.3'
      scan_severity:
        description: 'Trivy scan severity'
        required: false
        type: string
        default: 'CRITICAL,HIGH'
      golangci_version:
        description: 'golangci version to use'
        required: false
        type: string
        default: v1.52

permissions:
  contents: read
jobs:

  unit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491  # v5.0.0
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Tidy Modules
      run: |
        make tidy
    - name: Unit Test
      run: |
        make test
    - name: Parse Coverage
      uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
      with:
        flags: unittests  # optional

  lint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491  # v5.0.0
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Tidy Modules
      run: |
        make tidy
    - name: Config Go Lint
      id: golangci_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .golangci.yaml
    - name: Lint Go
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@82d40c283aeb1f2b6595839195e95c2d6a49081b # v5.0.0
      with:
        version: ${{ inputs.golangci_version }}
    - name: Config YAML Lint
      id: yamllint_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .yamllint
    - name: Lint YAML
      if: steps.yamllint_config.outputs.files_exists == 'true'
      uses: karancode/yamllint-github-action@0a904064817924fc6fb449a32f67f25bfacc48ae  # master
      with:
        yamllint_config_filepath: .yamllint

  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2.7.0
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
    - name: Scan Repo
      uses: aquasecurity/trivy-action@b5f4977b78f81fa3d48865ff0efcc6e279210235  # master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        hide-progress: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: ${{ inputs.scan_severity }}
        exit-code: '1'
    - name: Upload Report
      uses: github/codeql-action/upload-sarif@8f596b4ae3cb3c588a5c46780b86dd53fef16c52 # v3.25.2
      with:
        sarif_file: 'trivy-results.sarif'