name: test

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.20.3'
      scan_severity:
        description: 'Trivy scan severity'
        required: false
        type: string
        default: 'CRITICAL,HIGH'
      golangci_version:
        description: 'golangci version to use'
        required: false
        type: string
        default: v1.52

permissions:
  contents: read
jobs:

  unit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Tidy Modules
      run: |
        make tidy
    - name: Unit Test
      run: |
        make test
    - name: Parse Coverage
      uses: codecov/codecov-action@5ecb98a3c6b747ed38dc09f787459979aebb39be # v4.3.1
      with:
        flags: unittests  # optional

  lint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9  # v4.0.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Tidy Modules
      run: |
        make tidy
    - name: Config Go Lint
      id: golangci_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .golangci.yaml
    - name: Lint Go
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
      with:
        version: ${{ inputs.golangci_version }}
    - name: Config YAML Lint
      id: yamllint_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .yamllint
    - name: Lint YAML
      if: steps.yamllint_config.outputs.files_exists == 'true'
      uses: karancode/yamllint-github-action@0a904064817924fc6fb449a32f67f25bfacc48ae  # master
      with:
        yamllint_config_filepath: .yamllint

  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
    - name: Scan Repo
      uses: aquasecurity/trivy-action@7088d18dcb87884bc7b5a4000d5517d758e9aa13  # master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        hide-progress: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: ${{ inputs.scan_severity }}
        exit-code: '1'
    - name: Upload Report
      uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
      with:
        sarif_file: 'trivy-results.sarif'