name: test

on:
  workflow_call:
    inputs:
      go_version:
        description: 'Go version to use'
        required: false
        type: string
        default: '1.20.3'
      scan_severity:
        description: 'Trivy scan severity'
        required: false
        type: string
        default: 'CRITICAL,HIGH'
      golangci_version:
        description: 'golangci version to use'
        required: false
        type: string
        default: v1.52

permissions:
  contents: read
jobs:

  unit:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Tidy Modules
      run: |
        make tidy
    - name: Unit Test
      run: |
        make test
    - name: Parse Coverage
      uses: codecov/codecov-action@b9fd7d16f6d7d1b5d2bec1a2887e65ceed900238 # v4.6.0
      with:
        flags: unittests  # optional

  lint:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Setup Go
      uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5.1.0
      with:
        go-version: '${{ inputs.go_version }}'
    - run: go version
    - name: Cache Go Modules
      uses: actions/cache@6849a6489940f00c2f30c0fb92c6274307ccb58a # v4.1.2
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-
    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Tidy Modules
      run: |
        make tidy
    - name: Config Go Lint
      id: golangci_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .golangci.yaml
    - name: Lint Go
      if: steps.golangci_config.outputs.files_exists == 'true'
      uses: golangci/golangci-lint-action@971e284b6050e8a5849b72094c50ab08da042db8 # v6.1.1
      with:
        version: ${{ inputs.golangci_version }}
    - name: Config YAML Lint
      id: yamllint_config
      uses: andstor/file-existence-action@076e0072799f4942c8bc574a82233e1e4d13e9d6  # v2.0
      with:
        files: .yamllint
    - name: Lint YAML
      if: steps.yamllint_config.outputs.files_exists == 'true'
      uses: karancode/yamllint-github-action@0a904064817924fc6fb449a32f67f25bfacc48ae  # master
      with:
        yamllint_config_filepath: .yamllint

  scan:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
      with:
        egress-policy: audit

    - name: Checkout Code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Scan Repo
      uses: aquasecurity/trivy-action@cf990b19d84bbbe1eb8833659989a7c1029132e3  # master
      with:
        scan-type: 'fs'
        ignore-unfixed: true
        hide-progress: true
        format: 'sarif'
        output: 'trivy-results.sarif'
        severity: ${{ inputs.scan_severity }}
        exit-code: '1'
    - name: Upload Report
      uses: github/codeql-action/upload-sarif@662472033e021d55d94146f66f6058822b0b39fd # v3.27.0
      with:
        sarif_file: 'trivy-results.sarif'